apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-deployment
  template:
    metadata:
      labels:
        app: storage-deployment
        namespace: default
    spec:
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-nfs
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
          - name: vol
            mountPath: /test