  #  apiVersion: networking.k8s.io/v1
  #  kind: Ingress
  #  metadata:
  #    name: my-ingress
  #    annotations:
  #      nginx.ingress.kubernetes.io/rewrite-target: /
  #  spec:
  #   #  tls:
  #   #    - hosts:
  #   #      - thisisspartaa.leonid
  #   #      secretName: nginx
  #    rules:
  #      - host: thisisspartaa.leonid
  #        http:
  #          paths:
  #            - path: /
  #              pathType: Prefix
  #              backend:
  #                service:
  #                  name: {{ .Values.nginx.service.name }}
  #                  port:
  #                    number: {{ .Values.nginx.service.port }}
