{{- if .Values.nginx.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: nginx
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.nginx.secret.crt | b64enc }}
  tls.key: {{ .Values.nginx.secret.key | b64enc }}
{{- end }}